"""initial

Revision ID: 821b1b9cbabe
Revises:
Create Date: 2026-06-01 23:04:21.980493

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "821b1b9cbabe"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "babies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("birth_date", sa.Integer(), nullable=False),
        sa.Column("avatar_color", sqlmodel.sql.sqltypes.AutoString(length=7), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "active_breast_feedings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("baby_id", sa.Uuid(), nullable=False),
        sa.Column("started_at", sa.Integer(), nullable=False),
        sa.Column("current_side", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("last_switch_at", sa.Integer(), nullable=False),
        sa.Column("left_accumulated", sa.Integer(), nullable=False),
        sa.Column("right_accumulated", sa.Integer(), nullable=False),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["baby_id"],
            ["babies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_active_breast_feedings_baby_id"), "active_breast_feedings", ["baby_id"], unique=True)
    op.create_table(
        "feedings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("baby_id", sa.Uuid(), nullable=False),
        sa.Column("feeding_type", sa.Enum("BREAST", "BOTTLE", name="feedingtype"), nullable=False),
        sa.Column("side", sa.Enum("LEFT", "RIGHT", "BOTH", name="breastside"), nullable=True),
        sa.Column("amount_ml", sa.Float(), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("left_duration_seconds", sa.Integer(), nullable=True),
        sa.Column("right_duration_seconds", sa.Integer(), nullable=True),
        sa.Column("timestamp", sa.Integer(), nullable=False),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["baby_id"],
            ["babies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_feedings_baby_id"), "feedings", ["baby_id"], unique=False)
    op.create_table(
        "sleeps",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("baby_id", sa.Uuid(), nullable=False),
        sa.Column("start_time", sa.Integer(), nullable=False),
        sa.Column("end_time", sa.Integer(), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["baby_id"],
            ["babies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sleeps_baby_id"), "sleeps", ["baby_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sleeps_baby_id"), table_name="sleeps")
    op.drop_table("sleeps")
    op.drop_index(op.f("ix_feedings_baby_id"), table_name="feedings")
    op.drop_table("feedings")
    op.drop_index(op.f("ix_active_breast_feedings_baby_id"), table_name="active_breast_feedings")
    op.drop_table("active_breast_feedings")
    op.drop_table("babies")
    # ### end Alembic commands ###
